# Site settings
title: Full Contact Philanthropy
email: david.henderson82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Social sector commentary.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fullcontactphilanthropy.com" # the base hostname & protocol for your site
twitter_username: david_henderson
github_username:  dhenderson
author: David Henderson
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
